config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: {
                       sessions: 'users/sessions',
                       registrations: 'users/registrations'
                   }


  root 'navigator#index'


  get '/category_products', to: 'navigator#products_from_category', as: 'category_products'
  get '/product_details', to: 'navigator#product_details', as: 'product_details'


  post '/create_review', to: 'navigator#product_review', as: 'product_review'

  authenticated :user, lambda {|u| u.admin?} do
    scope "/admin" do
      resources :products
      resources :categories
    end
  end
end

app/views/common/_category.html.haml
.panel.panel-default
  .panel-heading
    %h4{:class=>"panel-title"}
      = link_to category.name, category_products_path(:category_id => category.id), :remote => true

app/views/common/_product.html.haml
.col-sm-3
  .product-image-wrapper
    .single-products
      .productinfo.text-center
        = link_to image_tag(attachment_url(product, :product_image, :fill, 300, 300, format: "jpg")), product_details_path(product_id: product.id ), :remote => true, :id => "image_#{product.id}"
        %h2="$" + product.price.to_s
        %p= product.title

app/views/common/_product_details.html.haml
.product-details
  .col-sm-5
    .view-product
      =image_tag attachment_url(product, :product_image, :fill, 300, 300, format: "jpg")

  .col-sm-7
    .product-information
      %span
        %h2= product.title
        %p= product.description
        %span
          %span= "$"+product.price.to_s

.category-tab.shop-details-tab
  =render partial: "common/reviews", locals: {product: product}

app/views/common/_reviews.html.haml
.tab-content
  .tab-pane.fade.active.in{:id=>"reviews"}
    .col-sm-12
      - if user_signed_in?
        %p
          %p
            %b Write Your Review
          =form_for(Review.new, url: {action: "product_review"}, remote: true, format: :json) do |f|
            .field
              .form-group
                = f.text_area :msg, {:class => "form-control"}
                = f.hidden_field :user_id, :value => current_user.id
                = f.hidden_field :product_id, :value => product.id
            .actions
              = f.button "Add Review", {:class => "btn btn-default pull-right", :type=>"submit"}
      - else
        .alert.alert-info
          =link_to "Sing-in to add your product review", new_user_session_path
    %p
      %b
        Reviews

    -product.reviews.each do |review|
      %ul
        %li
          %span.glyphicon.glyphicon-user
          = user_email review
        %li
          %span.glyphicon.glyphicon-time
          = review.created_at.strftime('%r')
        %li
          %span.glyphicon.glyphicon-calendar
          = review.created_at.strftime('%v')
      %p
        = review.msg
      %hr