config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: {
                       sessions: 'users/sessions',
                       registrations: 'users/registrations'
                   }


  root 'navigator#index'


  get '/category_products', to: 'navigator#products_from_category', as: 'category_products'
  get '/product_details', to: 'navigator#product_details', as: 'product_details'


  post '/create_review', to: 'navigator#product_review', as: 'product_review'

  authenticated :user, lambda {|u| u.admin?} do
    scope "/admin" do
      resources :products
      resources :categories
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<header id="header"><!--header-->
          <div class="header-middle"><!--header-middle-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="logo pull-left">
                            <a href="<%=root_url%>"><%= image_tag("logo.png") %></a>
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <div class="shop-menu pull-right">
                            <ul class="nav navbar-nav">
                                <% if current_user.try(:admin?) %>
                                     <li><%= link_to "Manage Categories", categories_path %></li>
                                     <li><%= link_to "Manage Products", products_path %></li>
                                <%end%>

                                <% if user_signed_in? %>
                                    <li><a href="#" class="active"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> <%= current_user.email %></a></li>
                                    <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class=>"disabled" %></li>
                                <% else %>
                                    <li><%= link_to "Sign in", new_user_session_path %></li>
                                <%end%>
                            </ul>

                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header-middle-->

        <div class="header-bottom"><!--header-bottom-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-9">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>

                    </div>
                    <div class="col-sm-3">

                    </div>
                </div>
            </div>
        </div><!--/header-bottom-->
    </header><!--/header-->


<div class="container">
  <%= yield %>
</div>

<footer id="footer" ><!--Footer class="navbar navbar-fixed-bottom"-->
        <div class="footer-top">
            <div class="container">
                <div class="row">
                    <div class="col-sm-7">
                        <div class="companyinfo">
                            <h2><span>e</span>-shopper</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </footer><!--/Footer-->

</body>
</html>